// Required for int*_t/uint*_t.
#include <stdint.h>

#include "AEConfig.h"

// #include "PrSDKAESupport.h"
#include "PrSDKClipRenderSuite.h"
#include "PrSDKDataStreamTypes.h"
#include "PrSDKDevice.h"
#include "PrSDKEffect.h"
#include "PrSDKEntry.h"
#include "PrSDKErrorSuite.h"
#include "PrSDKGPUDeviceSuite.h"
#include "PrSDKGPUFilter.h"
#include "PrSDKGPUImageProcessingSuite.h"
#include "PrSDKMemoryManagerSuite.h"
#include "PrSDKPixelFormat.h"
#include "PrSDKPixelFormatSuite.h"
#include "PrSDKPlugMemory.h"
#include "PrSDKPlugPPix.h"
#include "PrSDKPlugSuites.h"
#include "PrSDKPlugTimeline.h"
#include "PrSDKPlugUtilities.h"
#include "PrSDKPlugWindow.h"
#include "PrSDKPPix2Suite.h"
#include "PrSDKPPixCacheSuite.h"
#include "PrSDKPPixCreator2Suite.h"
#include "PrSDKPPixCreatorSuite.h"
#include "PrSDKPPixSuite.h"
#include "PrSDKQuality.h"
#include "PrSDKRenderCacheType.h"
#include "PrSDKSceneMetaData.h"
#include "PrSDKSequenceInfoSuite.h"
#include "PrSDKSequenceRenderSuite.h"
#include "PrSDKSmartRenderingSuite.h"
#include "PrSDKStringSuite.h"
#include "PrSDKStructs.h"
#include "PrSDKThreadedWorkSuite.h"
#include "PrSDKTimeSuite.h"
#include "PrSDKTypes.h"
#include "PrSDKVideoSegmentSuite.h"
#include "PrSDKWindowSuite.h"
//#include "Smart_Utils.h"

#include "SPBasic.h"